version: '3.4'
    
services:
  certbot:
    image: certbot/dns-google
    volumes:
      - ../../nginx/certbot/letsencrypt:/etc/letsencrypt
      - ../../nginx/certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./dns-api-secret-key.json:/etc/ssl-dns-plugin/secret.json
    ports:
      - "80:80" 
      # Run below command in interactive mode using docker-compose exec certbot [cmd]      
    # command: certonly --stageing --dns-google --dns-google-credentials /etc/ssl-dns-plugin/secret.json --dns-google-propagation-seconds 120  -d example.com 
  
    