version: '3.4'
    
services:

  server:
    volumes:
      # We use other nginx conf file in production 
      - ./nginx/conf/nginx-ssl.conf:/etc/nginx/conf.d/mysite.conf
      - ./nginx/conf/www:/usr/share/nginx/html
      - ./nginx/django/static:/usr/share/nginx/static
      # certbot-specefic, to give access to certificate
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/var/cache/nginx:/var/cache/nginx
      - ./nginx/certbot/dhparam.pem:/etc/ssl/dhparam.pem
    ports:
        - "443:443"
        - "80:80"

        