version: '3.4'
    
services:
  db:
    image: postgres
  webapp:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  server:
    image: nginx:latest
    volumes:
      - nginx/mysite.conf:/etc/nginx/conf.d/mysite.conf
      - nginx/www:/usr/share/nginx/html
    depends_on:
      - webapp  
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  
    