version: '3.4'
    
services:
  db:
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  webapp:
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
  server:
    ports:
        - "443:443"
        - "80:80"
  

   