version: '3.4'
    
services:
  db:
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  webapp:
    volumes:
      - .:/code
  server:
    volumes:
      # We use other nginx conf file in production 
      - ./nginx/mysite-certbot.conf:/etc/nginx/conf.d/mysite.conf
      - ./nginx/www:/usr/share/nginx/html
      # certbot-specefic, to give access to certificate
      - ./nginx/certbot/var:/var
      - ./nginx/certbot/etc:/etc
    ports:
        - "443:443"
        - "80:80"
    environment:
      - NGINX_PORT=80    
  

   