version: '3.4'
    
services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  webapp:
    volumes:
      - .:/code
  server:
    ports:
      - "80:80"
      - "8080:8080" 
    environment:
      - NGINX_PORT=80      

  