version: '3.4'
    
services:
  db:
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  webapp:
    volumes:
      - .:/code

  server:
    volumes:
      # We use other nginx conf file in production 
      - ./nginx/conf/nginx-ssl.conf:/etc/nginx/conf.d/mysite.conf
      - ./nginx/conf/www:/usr/share/nginx/html
      # certbot-specefic, to give access to certificate
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/var:/var
      - ./nginx/certbot/dhparam.pem:/etc/ssl/dhparam.pem
    ports:
        - "443:443"
        - "80:80"
    
  

   