version: "3.4"

services:
  
  devenv:
    build: 
      context: ./dev
    ports:
      - "3000:3000"
      - "3001:3001"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata 
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
   

  webapp:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    working_dir: /code/app/  
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi 

  server:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf/mysite.conf:/etc/nginx/conf.d/mysite.conf
      - ./nginx/conf/www:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - webapp
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
