FROM node:latest

RUN DEBIAN_FRONTEND=noninteractive apt update

RUN DEBIAN_FRONTEND=noninteractive npm install --global gulp-cli postcss-cli
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3-venv
